ROW_NUM = 25
COL_NUM = 50
SQUARE_LENGTH = 10
WINDOW_WIDTH = SQUARE_LENGTH * COL_NUM
WINDOW_HEIGHT = SQUARE_LENGTH * ROW_NUM
SOLDIER_IMG = "soldier.png"
GRASS_IMG = "grass.png"
FLAG_IMG = "flag.png"
SCREEN_COLOR = (0, 100, 0)
NUM_OF_MINES = 10
NUM_OF_GRASS = 5
EMPTY = 0
FLAG = 1
MINE = 2
GRASS = 3
FLAG_HEIGHT = 4
FLAG_WIDTH = 3
MINE_WIDTH = 3
MINE_HEIGHT = 0
GRASS_WIDTH = 3
GRASS_HEIGHT = 0

GRASS_SIZE = (4, 4)
MINE_SIZE = (3, 1)
SOLDIER_SIZE = (4, 2)
FLAG_SIZE = (4, 3)
MINE_SHADOW = 4
GRASS_SHADOW = 5
FLAG_SHADOW = 6

IMG_SOLDIER = 'soldier.png'
IMG_GRASS = 'grass.png'
IMG_FLAG = 'flag.png'
IMG_MINE = 'mine.png'
GREEN = (138, 201, 38)

BACKGROUND_COLOR = GREEN

SQUARE_LEN = 30
