ROW_NUM = 25
COL_NUM = 50

NUM_OF_MINES = 10
NUM_OF_GRASS = 20

EMPTY = 0
FLAG = 1
MINE = 2
GRASS = 3
MINE_SHADOW = 4
GRASS_SHADOW = 5
FLAG_SHADOW = 6

GREEN = (138, 201, 38)
BACKGROUND_COLOR = GREEN
BLACK = (0, 0, 0)
DARK_BACKGROUND_COLOR = BLACK
LIGHT_GREEN = (118, 238, 0)

SQUARE_LEN = 20

WINDOW_HEIGHT = ROW_NUM * SQUARE_LEN
WINDOW_WIDTH = COL_NUM * SQUARE_LEN

FONT_NAME = 'Calibri'
FONT_SIZE = 50
FONT_COLOR = (0, 0, 0)

GRASS_SIZE = (4, 4)
MINE_SIZE = (3, 1)
SOLDIER_SIZE = (2, 4)
FLAG_SIZE = (4, 3)

IMG_SOLDIER = 'soldier.png'
IMG_GRASS = 'grass.png'
IMG_FLAG = 'flag.png'
IMG_MINE = 'mine.png'
IMG_EXPLODE = 'explosion.png'
